### ISSUE TITLE
Is possible to add fields to Gallery Settings?

### ISSUE THREAD

**Issue by rahulnever2far** [AdvancedCustomFields/acf#12]
I'm trying to add a custom field to Gallery Settings. Is it possible with ACF or its Pro version?

![chrome_2017-12-14_17-49-56](https://user-images.githubusercontent.com/3503359/33992107-59b393e8-e0f7-11e7-9c01-1281b93673f3.png)

**Comment by elliotcondon** [comment]
Hi @rahulnever2far 

Thanks for the question. Unfortunately, we have not yet added integration with WP galleries.
The problem is that a gallery is saved as a 'shortcode' within the content editor and does not provide an 'ID' that can be used to save meta to.

I'm not sure that I have any solutions for this at the moment, but hope to find one in the future.

**Comment by rahulnever2far** [comment]
Thank you for clarifying.

I have a solution but it's very complex. That's why I was wondering if it's possible to do it with AFC.
