### ISSUE TITLE
5.8.0-beta4: A lot of javascript rendered in frontend

### ISSUE THREAD

**Issue by jfax** [AdvancedCustomFields/acf#151]
When updating from beta3 to beta4 a great amount of javascript-files are rendered in frontend, for example:
/wp-includes/js/dist/vendor/react.min.js

Maybe this could help:
https://wordpress.org/support/topic/too-many-js-files-from-wp-includes-js-dist/

**Comment by elliotcondon** [comment]
Hi @jfax 

This issue is due to a change we made in beta-4 which enqueues out JS in the "enqueue_block_assets" action.
This seems to also be run on the front-end and explains why all the WP blocks JS is being enqueued.

The fix for this issue is to change "enqueue_block_assets" to "enqueue_block_editor_assets" in the "/pro/blocks.php" file on line 383

**Comment by elliotcondon** [comment]
Duplicate: https://github.com/elliotcondon/acf/issues/762

**Comment by jfax** [comment]
fixed in beta4.1, thanks a lot
