### ISSUE TITLE
get_field_object() by name fails

### ISSUE THREAD

**Issue by Semaho** [AdvancedCustomFields/acf#156]
I don't know if it's a bug or if I've done something wrong, so I'm sharing what I've dug so far.

I have a field — let's call it `my_field` — nested in a group. 
`get_field_object('field_12345')` works (field key).
`get_field_object('my_field')` doesn't work (field name).

Here is the call stack :
- get_field_object
- acf_maybe_get_field
- acf_get_meta_field
- acf_get_reference
- acf_get_metadata
- get_metadata

`acf_get_metadata()` is called with `$hidden=true`, prefixing my field name with a `_`. 

So `get_metadata` tries to reach `_my_field` instead of `my_field`. I can see `my_field` as a key of the meta cache, so I tried the following :

```
function test($value, $post_id, $name)
{
    return $name;
}
add_filter("acf/pre_load_metadata", "test", 10, 3);
```

This short-circuits the name search and returns `my_field` without the underscore. 
This is obviously a *hack* but then `get_field_object('my_field')` finally works.

Also, `get_post_meta($id, 'my_field', true)` works too.

Why is my field considered as hidden? What did I miss?

**Comment by elliotcondon** [comment]
Hi @Semaho 

For the given post, does this "my_field" contain a value in the database?

The `get_field_object()` function will need to perform some extra lookups if you are using the field name vs field key. These lookups check if a "reference value" exists.

It sounds like you are trying to load the field settings of "my_field" when no value yet exists. This is a limitation of the plugin.

**Comment by Semaho** [comment]
Hello @elliotcondon ,

This is why I added a note about `get_post_meta($id, 'my_field', true)` working, `my_field` does have a value in postmeta table (doubled checked, function & DB).

For info, I'm trying to get the field settings by `name` because field groups are translated (WPML), and the `key` changes between languages.

**Comment by elliotcondon** [comment]
Hi @Semaho 

Thanks for the reply.

As well as a value for "my_field", can you please check that a value exists for "_my_field"?
This underscore version of the value is used to connect the field with the value, which we refer to as the "reference value".

If the reference value does not exist, this may help explain why the field is not being found.
If the reference value does exist, perhaps the problem will be related to the field key not matching the field for the current language.

Can you please also confirm that you have edited this post in the wp-admin and saved the post allowing ACF to save its values/reference values?

**Comment by Semaho** [comment]
> As well as a value for "my_field", can you please check that a value exists for "_my_field"?

Does not exist

> Can you please also confirm that you have edited this post in the wp-admin and saved the post allowing ACF to save its values/reference values?

Good guess, this is not what's happening. 
However, getting my value is not an issue. In this case, all I'm trying to do is to get the labels of select/radio/checkbox fields by using `get_field_object ` by name (understand: get the field array and then access `choices`).

Getting the field object by `key` is working. Can we expect the same while getting it by `name` or is it mandatory to save the post through the WP admin?

Thank you!

**Comment by elliotcondon** [comment]
Hi @Semaho 

Thanks for all the info, this is very helpful.

The `get_field_object()` function requires the "field reference" value to exist. This is a limitation of the function which we hope to improve in the future. The reason for this logic is due to ACFs ability to allow multiple fields to use the same name.

For example, you may have 2 field groups which both contain a field called "image". When you call `get_field_object('image')`, ACF does not understand which "image" field to return. Returning the wrong field by guessing could lead to errors in the template code.

If you provide the field key, instead of a name, ACF does not need to lookup the "reference value" because each key is unique and ACF knows exactly which field to return.

Perhaps you could try using the `acf_get_field()` function instead. This is an undocumented function, but one that is used in the ACF code base to load fields. You can provide a "field name" as the $id parameter, and ACF will lookup the field via name. That said, if two fields contain the same name, you may run into issues loading the correct field as mentioned above.

This is why we save the "reference value" when saving a value.
I hope this information is helpful to understanding the problem.

**Comment by Semaho** [comment]
Lifesaver ! 🥇  

We actually cared about not having same names in different groups for another reason so this is perfect.

Thank you very much Elliot.  
Should I let you manage this issue in case you'd like to keep it, or just close it ?

**Comment by elliotcondon** [comment]
Hi @Semaho 

Thanks for the reply.
We can close this for now.
