### ISSUE TITLE
"Unload Prompt" bug still exists in final version of ACF 5.8

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#182]
Hi Elliot,

I had reported this in issue #170 , but unfortunately the "Unload Prompt" bug as you named it still exists in the final version of ACF 5.8.

Thanks,
Nick.

**Comment by nick6352683** [comment]
Let me start by apologizing for stealing you away from your child !!!

Here is the video (no sound) - it happens only with Text fields, sometimes with the WYSIWYG field, but never with the color picker, select, etc...

 https://www.youtube.com/watch?v=OG07Ss15e5E&feature=youtu.be

Thanks again.

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks mate. I'll spend some time testing this out today and will be in touch.

**Comment by elliotcondon** [comment]
Hi @nick6352683 

I've just spent some time testing the issue and can confirm the unload prompt is incorrectly showing, however, I can also confirm that the unload prompt is not coming from ACF.

I believe this prompt is coming from the core Gutenberg editor which believes a change has been made after saving the post. I'm not sure how to fix this as the problem lies outside of ACF's codebase.

**Comment by nick6352683** [comment]
I appreciate that Elliot.
