### ISSUE TITLE
Options page values not saved in database until I press the update button.

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#203]
Hi Elliot,

- latest ACF Pro (5.8.2), latest WP (5.2.2).

1. I have successfully created an Options page, In the options page all I have are a number of True/False fields using the Stylized UI. 
2. In a new website these field values are not getting registered until I go to the Optins page and press the Update button. Once I update the Options page all is fine...

Is this a bug, or I need to do something?

Thanks,
Nick.

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks for the topic. This all sounds like expected behavior.

Creating an ACF field (in the admin UI) won't actually save any values into the DB.
It is only when you edit a post, user, term, options page, etc and click the "Update" button that any fields in that form are saved to the "meta" or "options" tables.

**Comment by nick6352683** [comment]
Thanks Elliot for the clarification.
