### ISSUE TITLE
Feature Request: Front End for ACF Blocks

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#212]
Hi Elliot,

I know that my requests are never easy, so I want to apologize beforehand... 

I don't have to tell you of that using Gutenberg blocks vs Custom fields has some distinct advantages: smaller database, easier import export, even easier templating (depending how you set up everything), just to mention a few...

That said, it would be great if we could also somehow add/edit these ACF Blocks from the frontend.  The saved data of course will go into the post, and not in the table where the custom fields get stored. I think eventually this is where everything will end up going anyway, so the sooner we (actually you...) come up with a solution for this, the better. Nobody has done anything remotely like this for the Gutenberg Blocks.

Thanks, and sorry again,
Nick.

**Comment by elliotcondon** [comment]
Hi Nick

Thanks for the topic. You're requests are great, but yes, not easy :)

Front end editing has long been a hot topic for WordPress, and I wonder if the WP team are already thinking about it. I agree that this is an important feature, but don't agree that ACF should be the ones to develop it.

I say this because "blocks" are an abstract idea that plugin developers like ACF, coblocks, blocklab, jetpack, woocommerce and others extend. The term "abstract" here is an important one.

Because all of our blocks extend from a single API, it makes much more sense to create a "global" front end editing experience for all blocks (not just ACF).

I suspect there are developers already working on a front end editing API for all blocks. If not, perhaps this would be an excellent project to dive into for yourself!

**Comment by nick6352683** [comment]
Thanks Elliot,

I gave it a shot...

Quote: "... If not, perhaps this would be an excellent project to dive into for yourself!"... Ha, you are funny !
