### ISSUE TITLE
Updating from 5 Beta to the latest

### ISSUE THREAD

**Issue by kuraga** [AdvancedCustomFields/acf#286]
Hello, @elliotcondon !

According to #285 , I'm willing to update my ACF 5 Beta to the latest version of ACF.

**My aim is: to prevent data corruption.** (Even though I will have a backup.)

And one more note: seems like ACF 5 Beta behaves like PRO (that's why I used it.)

I have some questions:

1. Is it possible to downgrade from PRO to standard version (sure with features dropping)? If yes, is it data safe?

2. (if p.1's answer is _Yes_) Will such downgrading erase PRO _settings_ (not features)? Or will they be restored after subsequently buying a PRO?

3. (if p.1's answer is _Yes_) If I put 5.8.9 (standard - not PRO) version code instead of 5 Beta: will it start database update mechanisms? Is it data-safe? Or I have to do something else?

4. If I will:
    a. buy a PRO version,
    b. enter License key in "ACF -> Updates",
    c. click some "Update" button,
will it start database update mechanisms? Is it data-safe? Or I have to do something else?

Thanks very much!

**Comment by elliotcondon** [comment]
Hi @kuraga 

Thanks for the questions. I'll do my best to answer them below:

1. Yes. This is fine. No data will be lost when changing from ACF to ACF PRO (and visa-versa).
2. No data will be changed / erased.
3. Yes. Two DB upgrade processes will exist for the versions "5.0.0" and "5.5.0". Because you are currently using "5.0.0-beta", I would advise you to edit your `wp_options.acf_version` value in the DB from "5.0.0-betaxxx" to "5.0.0". This will prevent the first upgrade from running which will not be needed.
4. Activating a license key will enable plugin updates. It is only after upgrading to the new version that a potential DB upgrade process will be available.

My advice: Backup your DB, and manually upgrade to the latest version. Remember to edit the `wp_options.acf_version` DB value, and then run the DB upgrade prompt.

If you run into any trouble, please be sure to contact our support team here: https://www.advancedcustomfields.com/contact

**Comment by kuraga** [comment]
@elliotcondon , thank you very much for reply!

By "manually update" do you mean "update plugin's directory with new code"? (I just don't understand: when upgrade process will be started...)

**Comment by kuraga** [comment]
Update: I think, I will update to 5.0.0 (not Beta) manually and then automatically to the latest version...

**Comment by elliotcondon** [comment]
Hi @kuraga 

Yes. By "manually update" I mean delete the plugin completely and replace it with the newest version 5.8.9.

Please note that there is no automated upgrade process. If a DB upgrade is needed, an admin notice will appear requiring you to click a button to initiate the upgrade.

**Comment by kuraga** [comment]
Well seems like I have updated my ACF.

1. My `wp_options.acf_version` already was `5.0.0`.
2. I replaced plugin's directory with new version' directory.
3. I clicked "Update database button" in Admin. Got success status.
4. My PRO fields' types became "Unknown". I adopted them and theme to non-PRO version (well, I have 2 PRO (repeater) fields of 75 total fields).

So, it's OK! Thanks very much, @elliotcondon !

P.S. I'm willing to read all the Changes 5.0.0...5.8.9 :smile:
