### ISSUE TITLE
Feature Request: Vertical alignment / Text alignment option for ACF blocks

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#335]
Hey Elliot,

thank you for adding the matrix control to ACF blocks. It's a helpful feature to modify the block content. I think there are two more essential block features, which can be helpful to modify the block content:

**Vertical alignment:**

<img width="273" alt="Bildschirmfoto 2020-07-20 um 13 52 46" src="https://user-images.githubusercontent.com/31563167/87935042-9ad56880-ca90-11ea-8489-419de775f39a.png">

**Text alignment:**

<img width="282" alt="Bildschirmfoto 2020-07-20 um 13 52 24" src="https://user-images.githubusercontent.com/31563167/87935067-aa54b180-ca90-11ea-8fe9-9bab220ae8c3.png">

With these additional block options, we don't have to add our own ACF fields for a standard option like text alignment. Can you add this function to the ACF blocks, too?

**Comment by elliotcondon** [comment]
@CreativeDive Ooh, this is a really good point. The new Matrix Alignment might be, upon reflection, "running before walking".

I'll add this to my to-do and will have a think about adding these in.

**Comment by elliotcondon** [comment]
@CreativeDive So I've just had a look into this, taking inspiration from various core blocks types (Columns, Paragraph and Group), and am in two minds about adding in the additional alignment toolbar buttons.

On the one hand, if we have Matrix alignment option, it does makes sense to also add in basic x and y alignments.
On the other hand, the core Group block doesn't provide these settings, and leaves that to the inner blocks.

Happy to continue the discussion, and please don't think I've lost interest in the enhancement. This may also get pushed out to a later release (after 5.9).

**Comment by CreativeDive** [comment]
@elliotcondon Thank you for response. I think the important point is the user experience. By working with blocks, this controls are the basic parts of blocks to change the alignments.

Currently I use additional ACF fields to do this. But this breaks the user experience. I think for this very basic feature, we should use the default way for WordPress blocks.

**Comment by elliotcondon** [comment]
I completely agree, the UX should drive these decisions. On that note, I've been thinking about the feature further and have a list of topics to discuss:

**Experimental**
It turns out that WP 5.5 may not include the MatrixAlignment control after all. This is still marked as experimental, which according to the WP core blog post, means it won't be included in the next release. On this note, I'm tempted to pull out this feature for now, and add it back in for WP 5.6.

**XY**
There appear to be 3 alignment toolbar buttons; Text align, Vertical align and the new Matrix align.
At first I though of these as x align, y align and xy align, however it may not be that simple. The Vertical align button performs the same "y" functionality of the Matrix align button, but the Text align does not. The Text align should align the text within the content, not the position of the content. 

This means that Vertical align and Matrix align are related, but the Text alignment button is not related, and can be used in conjunction. For example, this would be the list of possible toolbar button combinations that make sense:
- Text Align
- Text Align + Vertical Align
- Text Align + Matrix Align
- Vertical Align
- Matrix Align

Why am I going into so much detail with this? Mostly for my own reference, but also to allude to my next topic.

**Settings**
With the possible toolbar button combinations defined, we can now design the settings needed. The current Matrix Alignment implementation uses a setting name of "align_content". This was to bring consistency with the existing "align" setting. A separate setting will be needed for Text align. Perhaps "align_text"?

We can also introduce a variation to the "supports.align_content" setting which allows the developer to chose between "vertical" or "matrix". Currently, this setting is a `bool` which we could also keep to automatically determine which alignment toolbar is available depending on the WP version.

Here's some example code to demonstrate what these settings could look like:
```
array(
    'align' => 'wide',
    'align_text' => 'left',
    'align_content' => 'top',
    'supports' => array(
        'align' => true,
        'align_text' => true,
        'align_content' => 'vertical',
    )
)

array(
    'align' => 'wide',
    'align_text' => 'left',
    'align_content' => 'center center',
    'supports' => array(
        'align' => true,
        'align_text' => true,
        'align_content' => 'matrix',
    )
)
```

Returning back to the "UX should drive these decisions" statement. What are your instincts telling you about these settings? Does this feel natural, future proofed, etc? Or can you see some potential issues with this kind of implementation?

Thanks mate! I'm really looking forward to hearing your thoughts on this.

**Comment by nick6352683** [comment]
I just tested WP 5.5 beta2 and the Matrix control is included, (at least for now) as I did not have the Gutenberg plugin activated, 

That said, since ACF 5.9 beta 4 was released last week, I am furiously implementing the Matrix control to all my themes, while replacing the previous controls I had using ACF fields. Having to redo all that work, only to redo it all over again by the end of the year is just nuts on my end (its not just the code that has to be changed but also the content) - so PLEASE reconsider about removing the Matrix from 5.9, as even if it is removed from WP 5.5 we can always use it via the Gutenberg plugin, besides, no matter what, the Gutenberg plugin is always activated on all my sites.

It it matters at all, I'm for keeping the Matrix, and also adding the Vertical and Text Alignments if possible... 

Sorry for cutting in...

**Comment by CreativeDive** [comment]
@elliotcondon I can confirm with @nick6352683 the matrix control is included in the latest WP 5.5-beta3-48556 by default, without installed gutenberg plugin.

@elliotcondon Thank you for your thoughts on this feature. I think you've considered everything very well.

I think your example is future proofed. At the end it's always a theme developer decision, how we enable the alignment features on specific block. For example, the text alignment make no sense for a wrapper block, but it's a good option for an inner blocks, which includes content.

I think a possible switch between "matrix" or "vertical" on the "align_content" feature is a very good decision.

The text align feature should insert classes like "has-text-align-right".

**Comment by CreativeDive** [comment]
@elliotcondon Maybe in the future the matrix control could be included as an optional feature. Like the line-height option:

```
// Enable the custom line height support for core blocks
add_theme_support( 'custom-line-height' );	
```

We will see. I can not imagine that this feature will be deactivated.

**Comment by elliotcondon** [comment]
@nick6352683 @CreativeDive Thanks for both your replies. 

I'm a little confused why I wasn't able to find the AlignMatrix component in my WP 5.5 testing, but will happily check again today. If WP is including the component, it makes sense for ACF PRO 5.9 to also include it. I'll also begin development on the extra alignment controls today. This may require a beta5 release, but agree it will be worth it! 

Glad to have you both here to help test it out!

**Comment by elliotcondon** [comment]
Great news 🎉. I've just pushed an update with new "align_text" and "align_content" settings as described in https://github.com/AdvancedCustomFields/acf/issues/335#issuecomment-662756942.

The "align_text" setting can enabled like so:
```
acf_register_block_type( array(
    'name' => 'xxx',
    'title' => 'xxx',
    //'align_text' => 'center' Optional default value
    'supports' => array(
        'align_text' => true,
    )
));
```

The "align_content" setting can enabled like so:
```
acf_register_block_type( array(
    'name' => 'xxx',
    'title' => 'xxx',
    //'align_content' => 'top center' Optional default value
    'supports' => array(
        'align_content' => true,
    )
));
```

If the AlignMatrix component does not exist (previous versions of WP without Gutenberg plugin), the toolbar button will fallback to "vertical". This can also be selected as the alignment type like so:
```
acf_register_block_type( array(
    'name' => 'xxx',
    'title' => 'xxx',
    //'align_content' => 'top center' Optional default value
    'supports' => array(
        'align_content' => 'vertical',
    )
));
```

Looking forward to hearing your feedback 🙌.

**Comment by CreativeDive** [comment]
@elliotcondon Thank you, this is really cool. It looks like you just snap your finger and it works.

My test are completed and it works really fine. Now I can remove a lot of unnecessary fields inside the block field group, this is great! And the user can adjust the alignment, like a default WordPress block.

Here the code, how I manage the alignment class names:

```			
// Attribute "Text alignment"
if( isset( $block['align_text'] ) && $block['align_text'] ) {
	$classes[] = 'has-text-align-' . $block['align_text'];
}

// Attribute "Vertical content alignment"
if( isset( $block['supports']['align_content'] ) && $block['supports']['align_content'] === 'vertical' ) {
	$classes[] = 'is-vertically-aligned-' . $block['align_content'];
}

// Attribute "Content alignment"
if( isset( $block['supports']['align_content'] ) && $block['supports']['align_content'] === 'matrix' ) {
	$align_content = str_replace(' ', '-', $block['align_content'] );
	$classes[] = 'is-position-' . $align_content;
}
```

Great work and so many thanks!!!

The only thing, I think the position of the alignment controls should be positioned before the ACF "Switch to edit" button.

**Comment by elliotcondon** [comment]
@CreativeDive Fantastic!

Yeah, this came together super quickly in code. I'll be sure to update the docs with code examples on how best to read the alignment attributes, but the way you are doing it looks great.

I'll have a look at the toolbar positioning too. This actually raises a great questions about how HOC work in React.

**Comment by elliotcondon** [comment]
Good news. I've fixed the order of alignment buttons to read: Block width alignment, Content alignment, Text alignment, Edit mode  🎉. This feels natural when compared to core blocks - thanks for the feedback!

**Comment by JiveDig** [comment]
Great convo yall, and the implementation is 💯
