### ISSUE TITLE
Possible Date/Time bug

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#336]
Hi Elliot,

I re-created your Restricted block from this page https://www.advancedcustomfields.com/blog/acf-5-9-exciting-new-features/

Of course I also created the 2 ACF fields needed to make the block work, which was easy to determine their names simply by looking at the provided code.

1. Now, everything works perfectly, but if I change the Language in WordPress (Settings -> General), the content is ALWAYS expired. Changing the language back to US English, the block works perfectly again, and the innerblock content is been displayed. Am I doing something wrong, or is this a bug?

2. Back to the restricted block again - I'm setting the times according to the local time set in WordPress, which in my case the Time zone is set to "Los Angeles", but the Restricted block executes the times in UTC, which in my case I'm -7 hours. Is the supposed behavior, or even better, is a way to "force" ACF to execute the times according to the time zone set within WordPress?

P.S. If it helps, both the Display and Return Formats for the Date/Time fields are to the 3rd option, ie: July 25, 2020 10:58 pm, do you think changing the formats to maybe the 4th choice (2020-07-25 22:58:24), issue 1 would be solved?

UPDATE: After testing, changing the time format to the 4th choice (2020-07-25 22:58:24), fixes issue 1, which is strange because the documentation says that the value is always stored as (YYYY-MM-DD HH:II:SS) in the database, so how it is displayed should not make an impact in the calculations... Am I missing something, or is this a bug?

Thanks in advance, Nick.

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks for the questions.

1. It is most likely that the `strtotime()` conversion is failing, due to translated month names. A solution for this would be to select a `return_format` that returns only numeric values such as `Y-m-d H:i:s` - however, you will then require additional code to display this for the reader.

2. The ACF Date, Time and DateTime fields do not save any timezone reference with the value. You may require a 3rd party field type to store this extra data, or perhaps some JS to customize the date picker args.

3. Yes.

4. There is no bug here. The value is indeed saved into the DB as "YYYY-MM-DD HH:II:SS" - which you can check to confirm. The value is "formatted" when loaded using the `return_format` setting.

Hope that info helps 👍

**Comment by nick6352683** [comment]
Actually it does help, thanks.
