### ISSUE TITLE
BUG: The get_field_object() function don't work with field name.

### ISSUE THREAD

**Issue by adthonb** [AdvancedCustomFields/acf#351]
Hello

I try to get data from the field name with get_field_object() but it returns a false value. I digging into ACF code and I see some point that causes this issue.

The get_field_object() use acf_maybe_get_field() to retrieve a field data but acf_maybe_get_field() have 3rd parameter that set to false for preventing get a field data by name. Please see

```
function acf_maybe_get_field( $selector, $post_id = false, $strict = true ) {
        ...
	// Lookup field loosely via name.
	if( !$strict ) {
		return acf_get_field( $selector );	
	}
	
	// Return no result.
	return false;
}
```

Then I can't get field data with get_field_object() but your document (https://www.advancedcustomfields.com/resources/get_field_object) tells $selector can be field name. Please check and fix this. I feel bad with your support that doesn't answer my question

**Comment by elliotcondon** [comment]
Hi @adthonb 

Thanks for the topic. You are correct in identifying that the `get_field_object()` function uses `acf_maybe_get_field()` in a "strict" mode. This is to prevent false matches when multiple fields share the same name.

ACF uses a concept of "reference values" to correctly lookup the Field Object from a meta value. If you look in the wp_postmeta table for a given post, you will see two meta rows for each value like so:
```
hero_title = Welcome to our website
_hero_title = field_234jhg345
```

The "underscore" meta row is considered a "reference value" that ACF uses in the `get_field_object()` function to find the corresponding field. There is no need to search by name when the reference value exists.

Is it possible that your post does not contain reference values because the data was populated from a source outside of the WP "Edit Post" admin screen?

**Comment by adthonb** [comment]
Hello @elliotcondon 

Thank you for answer me. I try to get array data from the field outside Edit Post. I set up fields and use `get_field_object()` from WP Page Templates on my theme. I just want to make a custom dropdown with ACF value.

![acf](https://user-images.githubusercontent.com/18661601/89645035-31a08280-d8e3-11ea-9468-ffb9a3b583fd.jpg)

**Comment by elliotcondon** [comment]
Hi @adthonb 

Thanks for the reply and context. In this case, please use the function `acf_get_field()` and pass in either the field name or key. This function will load the field directly, without any need of "reference values".
