### ISSUE TITLE
XSS vulnerability inside the Wordpress Panel

### ISSUE THREAD

**Issue by xandjiji** [AdvancedCustomFields/acf#371]
The field label isn't being sanitized for XSS attacks.

Since the user is authenticated when this happens, it can lead to very dangerous scenarios (an attacker can use Ajax requests to vandalize the Wordpress database or even steal the authenticated user's cookies).

![image](https://user-images.githubusercontent.com/11613697/91236249-d3123b80-e70d-11ea-967b-2624cc745eb0.png)

**Comment by elliotcondon** [comment]
Hi @xandjiji 

Thanks for the bug report. I can confirm we are aware of this issue, and will begin work shortly on a solution for correctly sanitizing all HTML safely to avoid XSS vulnerabilities through HTML attributes. 

The problem is not only with Field labels displayed in the "Edit Field Group" admin screen, but more widespread throughout the plugin.

We appreciate your help and patience 👍.

**Comment by elliotcondon** [comment]
@xandjiji Can confirm this issue will be fixed in version 5.9.6
