### ISSUE TITLE
weird jQuery issue where block can only be control from a metabox

### ISSUE THREAD

**Issue by openbayou** [AdvancedCustomFields/acf#429]
Hello,

I'm having a weird problem with a block. I'm looking for a way to do some jQuery work to hide fields but still remain shown so that they are stored when saving a post. To start, I simply made a simple script: have a button and when it's clicked, change the color of a background. Set the ID of the button to #test and a text field to have the background changed with an ID of #output. This is also using the testimonial block that's in the manual when registering a new block and the default 2020 theme.

I enqueued the script and the JS shows up when writing a new post. 

But when I added the testimonial block, when you click on the button, the background color doesn't change.

So I added a metabox and had the same thing in the block: a button called #test and a text field called #output that's used to change the background color. When you click on the button in the metafield, the #output text field in the metabox doesn't change color but the #output text field in the block does change color.

I'm stumped at what to do next. Is this a bug in ACF? Enclosed is a video demonstrating the problem and below is the JSON output of the block and metabox plus the JS file that's enquired.

Link to JSON: https://www.dropbox.com/s/qzuvoygwp70v00k/acf-export-2020-12-31.json?dl=0

JS file: https://www.dropbox.com/s/8797uqthbrxkxx6/editor.js?dl=0

Thanks.

https://user-images.githubusercontent.com/4471306/103399455-da57b480-4b06-11eb-92e2-8f56ed291e1f.mov

**Comment by elliotcondon** [comment]
Hi @openbayou 

Thanks for the topic. The issue here is a combination of timing and duplicate selectors. I'll answer the later issue first:

The reason why your metabox button is modifying the block field is simply due to the instructions you are handing to jQuery. I suggest that you inspect the HTML of the block's field and note that the input ID matches the selector in your JS code. Nothing is technically wrong here, but you may want to use unique ID's in the future for testing.

Onto the real issue - the reason why your block button is unresponsive is simply due to the timing of script execution. Your JS code will run during the "ready" event, which is fired when the page loads, before your block exists. This means that your block's button element doesn't exist, so the click event will never be added to that DOM element.

There are a few ways around this. One is to us an alternative event listener like so:
```
$(document).on( "click", '#test2', function() {
```

Another solution is to use our JS API and hook into the "new_field" action for your button:
https://www.advancedcustomfields.com/resources/javascript-api/#actions-new_field

Hope this is helpful. Good luck with your project 👍

**Comment by openbayou** [comment]
Thanks for the help.
