### ISSUE TITLE
No block options default value found for older blocks

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#435]
Hey @elliotcondon,

if I working with default alignment values for ACF blocks, I getting an issue with the default value.
For example, the block contains a default text align value like "center". This default value dosen't exists for older blocks which was added before I added this default value to acf_register_block_type(). But it works for new added blocks.

This is are the block options:

```
acf_register_block_type(
		array(
			'name' => 'heading',
			'title' => __('Heading', 'wphave'),
			'description' => '',
			'icon' => wphave_svg_icon( 'heading', $block_foreground ),
			'category' => 'theme-text',
			'keywords' => array( 'heading', 'headline' ),
			'mode' => 'preview',
			'align_text' => 'center', // --> Optional default value
			'supports' => array(
				'align' => array( 'left', 'center', 'right', 'wide', 'full' ),
				'align_text' => true, // --> Enable the text alignment control
				'mode' => true,
				'multiple' => true,
				'anchor' => true,
			),
			'render_template' => wphave_dir( 'inc/acf-blocks/heading/heading.php' ),
		)
	);
```

If I print the $block array of a new block everything is fine "[align_text] => center". The default value was set.
If I print the $block array of an older block "[align_text] => ". The default value was missing.

How I can solve this?

**Comment by elliotcondon** [comment]
Hi @CreativeDive 

Thanks for the topic. What you have described sounds like ACF's expected behavior for default values.

When saving a block that supports a property (such as "align_text"), that property value will always be saved within the block data - even if the property value was never changed/selected.

This is by design, and allows developers to adjust default values over time without running the risk of introducing site-wide changes to preexisting blocks. It's important to note that this behavior is the opposite from a core WordPress block which won't save property values that have not bee changed/selected.

Hope this information is helpful.
