### ISSUE TITLE
Wrong Field taken from other group with same Field Name ACF PRO 5.9.0

### ISSUE THREAD

**Issue by j0hannr** [AdvancedCustomFields/acf#444]
I have multiple *custom Post Types* with each a different `Field Group Key`, but some of them have the exact same Field by Name, Label and Field Type. 

When displayed with `ACF Forms` always the same Field is loaded (noticed by the Placeholder), but not the correct one for the specified *custom Post Type*.

(All other fields are loaded from the correct field group/custom Post Type within the same form.)

I assume the Field gets queried only by its Name without the `Field Group` or *custom Post Type*.

**Comment by elliotcondon** [comment]
Hi @j0hannr 

This sounds like something our support team will be happy to help with.

From a technical point of view, ACF is able to differentiate between fields because they all contain unique `key` properties. In some scenarios, it may be possible that ACF is incorrectly determining the field, but we would need to investigate this by analyzing your exact Field Group and Code setup.

When submitting your support ticket, please be sure to include the exact steps, code and Field Group export needed to replicate the issue by one of our support members 👍 .

https://www.advancedcustomfields.com/contact/

**Comment by j0hannr** [comment]
Thanks! 

Yes, by using the field or group `key` it does work.
