### ISSUE TITLE
The Matrix Control component does not show up with Gutenberg 10.3.2

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#481]
I'm not sure when this started but, with the latest WP and the latest Gutenberg installed (v10.3.2), the Matrix control does not show up on the toolbar. Disabling the Gutenberg plugin, the Matrix Control component is visible on the toolbar again. 

Note: Even thought the Matrix control is not available, any previous position setting is honored both of the front end and back end.

After 3 years I'm very tired of having to fix things when things get broken with almost every Gutenberg update, every 2 weeks !!!

**Comment by nick6352683** [comment]
Update: I rolled back the Gutenberg plugin and uncovered that until v10.2.1 the Matrix Control was working.  With the next update being v10.3.0 the Matrix Control is a no show on the toolbar,

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks for the heads up. Can you please also post this regression issue over on the Gutenberg GitHub repo?

The following line of code is taken from the ACF PRO plugin and shows how we are referencing the MatrixToolbar component. It's possible that the entire issue is due to a naming or location change to this component within the Gutenberg 10.3.2 release.
```js
const BlockAlignmentMatrixToolbar = ( wp.blockEditor.BlockAlignmentMatrixToolbar || wp.blockEditor.__experimentalBlockAlignmentMatrixToolbar );
```

**Comment by nick6352683** [comment]
Hi guys, after more than a week and we are getting nothing from these incompetent Gutenberg developers...

From the handbook I found the only documentation regarding the Matrix control, unfortunately there is no date when it was created or when if ever, it was edited. Could the answer lie somewhere here? I tried a few things, but was not successful, maybe someone like @CreativeDive or @elliotcondon will have better luck?

https://developer.wordpress.org/block-editor/reference-guides/components/alignment-matrix-control/

To be honest, it will not be the end of the world if we can't get a fix... I will resort of using a Select box instead, but the Matrix control looks so much better., and more modern..

**Comment by CreativeDive** [comment]
@nick6352683 The Gutenberg team lacks clear leadership. It seems that the Gutenberg editor is a playground for some developers. This is evident in many cases.

**Comment by nick6352683** [comment]
@CreativeDive You are going to love this... Gutenberg 10.5 was released a few hours ago. Of course the Matrix Control for ACF is not fixed, plus they added a few new goodies.

- With Gutenberg 10.5 activated the page loads are now about 250% slower.
- They added all around 16px of padding to the Cover block, which if you have a boxed theme, or some complex patterns where every pixel counts, things get broken. The fix is easy, with CSS just reset the Cover block to have 0 paddings again.
- In the back end, again, things get loaded about 2-3 times slower. The ACF preloading still does the job (define('ACF_EXPERIMENTAL_PRELOAD_BLOCKS', true);), but the moment you click on an ACF block, instead of seeing the block's settings in 1-2 seconds, you now have to wait 4,5 sometimes 10 seconds, I guess depending how many fields your block uses.
- Click and drag from the main inserter is kinda broken, and they have also introduced a few new bugs in general.

All this from about 20 minutes of testing and trying to fix things they are breaking left and right. I'm sure tomorrow I will find 20 more things that they broke..., again !

And this is 40% of the entire internet ! How screw up are the rest?

Of course looking and searching the release notes, just like the Matrix control, there is absolutely no control about the 16px padding for the Cover block. Deactivating Gutenberg 10.5 things go to normal.

There is no reason to now make CSS changes to any block that is around from day one, where themes and patterns are built around them, and just like that, they need to get fixed. I bet that they do zero testing using boxed themes, or themes that have dark backgrounds, or God forbid do some testing with themes that have more than 700px of content width. 

You were too nice when you said the Gutenberg team lacks leadership. Simply put, they are an embarrassment !

**Comment by nick6352683** [comment]
P.S. Gutenberg 10.5.2 fixes the slow page loads and block loads both on the front end, and back end. Everything else is the same from above...

**Comment by CreativeDive** [comment]
@nick6352683 Welcome to my world. I know, essential things become changes again, again, again ... again. It's very annoying for me and a lot of other theme and plugin developers.

You are sure version 10.5.2 fix the slow page load of the block editor? It's still super slow for me since 10.2. and 10.5.2

**Comment by nick6352683** [comment]
@CreativeDive , Yes I am sure about the slow load times on all my test sites, testing with Xampp - php 7.2x, Loading times were around 1 second (I have many plugins activated), and when 10.5 came around the loading times went to about 2.5 seconds. With Gutenberg 10.5.1 & 10.5.2 the loading times went down to the normal 1 second. There was apparently a bug in one of their API's that got fixed with 10.5.1.

The loading times in the backsite went back to normal as well...

P.S. Sometimes when I update a plugin, like Gutenberg and even ACF Pro, the browser cache does not fetch the updated resources, so make sure you clear the cache every time you update a plugin, both on the front end and backend.

Also, I have a suspicion that all these changes back and forth (at least as far as CSS), is not coming from the Gutenberg team, but from the CSS audit team that was created more than a year ago. These people think they are helping. but I think most of the recurring changes (and problems) comes because of their suggestions. I also think nobody over there tests things with boxed themes, and dark colored themes...

I am trying to be nice, but the Gutenberg project, especially the Full Site Editing, and the WordPress project in general, has turned into a "shit show!!!". This is 40% of the internet, and pretty much in it's current status, especially all the default themes, are an embarrassment. There are too many cooks in the kitchen, many from different companies with different agendas, and nobody seems to be in charge, or at the very least nobody takes any responsibility. 

And we still have no response regarding the Matrix control - and time is ticking...

**Comment by vdwijngaert** [comment]
Hey @elliotcondon, looks like I'm still a member of @AdvancedCustomFields/testers. I see the latest release on the repo is 5.8.10 (May 2020). Would you mind doing a release or pointing me to the steps to build the latest stable myself? Some steps to reproduce this issue would come in useful as well. Thanks!

Hey @nick6352683 and @CreativeDive. I'm sorry you guys had this experience with Gutenberg. The point of the Gutenberg feature plugin is to get the latest version of the editor out there as soon as possible, so enthusiasts like you and I can join in testing bleeding-edge features, so that we can be confident enough to include a well-tested and stable version in WordPress core. Sometimes regressions happen after releasing a new version, but we try to spot and fix these things by consistently releasing one or more _release candidates_ of the next version, as part of the release process (which happens twice a month). Feel free to check out [10.6-RC1](https://github.com/WordPress/gutenberg/releases/v10.6.0-rc.1), which is due for a stable release next wednesday.

Unfortunately, sometimes experimental features (like the `BlockAlignmentMatrixToolbar`) get changed or even removed, that's why they are marked as _experimental_. Nevertheless, I'll try and see where I can chime in to get this issue resolved in the next release, which is 10.7.

I'm sorry you felt this way about how your issue is being handled. While it's no excuse, please know that Gutenberg is moving at an incredibly fast pace. A lot of people are working really hard on getting Gutenberg where it needs to be. 

In the [last month alone](https://github.com/WordPress/gutenberg/pulse/monthly):

* 123 authors have pushed 480 commits to trunk and 1,494 commits to all branches. 
* On trunk, 2,262 files have changed and there have been 69,769 additions and 52,752 deletions. 
* 460 pull requests were merged and 303 issues closed.  
* 11 releases were published.

For me personally, I find that mind blowing. Even more so because this is an open source project, and most of these people are working on this in their own time. I've only recently started regularly contributing as a way of giving back, and I absolutely love it. The Gutenberg team is always on the lookout for people who are willing to donate a little bit of their time to the project. There's a lot of ways to do so, no coding required. Feel free to check out the [Contributor Guide](https://developer.wordpress.org/block-editor/contributors/) if you'd like to help us make a better and more stable version of Gutenberg. You can also keep track of progress on [make.wordpress.org](https://make.wordpress.org/core/tag/gutenberg/).

Should you happen to be reporting another issue in the future, here's what you can do to increase the odds of a swift resolution. The editor gets pre-filled with an [issue template](https://github.com/WordPress/gutenberg/blob/trunk/.github/ISSUE_TEMPLATE/Bug_report.md) describing in detail how to format your issue, what steps to try yourself and what else you can include that can help the triage team make sense of your issue and get it under the attention of the right people. If you think your issue went by unnoticed, feel free to drop us a line in the #core-editor slack channel (see the link in the contributor guide).

**Comment by nick6352683** [comment]
Thank you @vdwijngaert ... Just a quick note. In the past (in 2018 or 2019) I tried Slack, and I got a quick response. The response was post it at Github. In the future I will try both places, and follow your advice... thanks for helping out, I guess @elliotcondon you have the final say for this...

**Comment by nick6352683** [comment]
With the latest ACF Pro update (5.9.6) this issue is now fixed. Special thanks from me to @elliotcondon , @vdwijngaert , and @CreativeDive for having my back... I don't have to change my code after all !
