### ISSUE TITLE
Case sensitive Issue on <clipPath> / <clippath> and InnerBlocks

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#514]
Hey @elliotcondon,

First of all, I would like to let you know that I am sad that you will no longer be part of ACF in the future.
It's hard to imagine that you will no longer be a contact for. Even if I understand your decision and think that it is the right decision for the plugin itself in the long run.

I wish you the best for your future.

I have over-noticed an issue using inner blocks. When I work with `<clipPath>` in the HTML markup, the HTML tag is written in lower case `<clippath>` in the editor. As a result, the ClipPath is not displayed correctly. Instead, it works very well in the frontend. Can this issue be related to how ACF changes code when inner blocks are part of a block?

**Comment by elliotcondon** [comment]
Hi @CreativeDive,

That is so nice of you to say! Thanks for supporting my work, and my decision to ensure the project's success 🙌.

I can confirm this bug will be due to the "JSX Parser" which converts the server-side generated HTML into JSX within the browser. This parser loses case-sensitive HTML tags, which we will need to add back in manually. Luckily, most HTML tags are not case sensitive, but it appears that `<clipPath>` is. I'll add a note to develop some extra logic that allows this tag.

**Comment by CreativeDive** [comment]
@elliotcondon Thank you.

**Comment by CreativeDive** [comment]
@mattgrshaw thanks works like expected since ACF 5.9.8

**Comment by mattgrshaw** [comment]
@CreativeDive Glad to hear!
