### ISSUE TITLE
What we can expect from Delicious Brains as the new owner of ACF in the future?

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#525]
Hello @elliotcondon, 

Hello @deliciousbrains ( @bradt / @mattgrshaw ) the new owner of ACF.

Congratulations :confetti_ball: on the acquisition of ACF [https://deliciousbrains.com/epic-wordpress-announcement/](https://deliciousbrains.com/epic-wordpress-announcement/)

I'm opening this topic because I think many ACF users have questions about the acquisition of ACF. :eyes: Many users like me and a lot of others have contributed a lot to improve ACF even further in recent years. This includes feature requests, bug reports, and the discussion with @elliotcondon here on Github.

Elliot has always been very honest and open to suggestions, feature requests and bug reports. :raised_hands: Now that the time has come for Elliot to be less and less involved in ACF (you can tell by the response on Github here), I wonder how @deliciousbrains will interact with user inquiries in the future?

Working with WordPress has changed a lot in the last few years and the future will be a future with block-based themes.

@elliotcondon has made life a lot easier for all ACF users with the awesome PHP block solution. :muscle: Logically, many expectations relate to the expansion and improvement of the ACF block functionalities.

As a one man band, progress with increasing changes in WordPress was associated with long waiting times. Which is completely logical to me. With @deliciousbrains and more man power, maybe that will change in the future?

What can we expect in the future and what not? I would like to mention a few topics here and ask directly how @deliciousbrains feels about these open inquiries.

Some requests are essential in my opinion, others would improve the user experience with ACF and the block editor.

# :pushpin: Essential

### Blocks essential markup differences for innerBlocks
https://github.com/AdvancedCustomFields/acf/issues/465

### Essential markup differences for Blocks
https://github.com/AdvancedCustomFields/acf/issues/470

# :rocket: Most Wanted Feature Request

### Inner Blocks for repeater fields
https://github.com/AdvancedCustomFields/acf/issues/298

# :checkered_flag: Feature Requests

### Left / Right Direction for ACF Block Options
https://github.com/AdvancedCustomFields/acf/issues/356

### Full Height Toggle for ACF Blocks
https://github.com/AdvancedCustomFields/acf/issues/417

### Horizontal / Vertical resizer for ACF blocks
https://github.com/AdvancedCustomFields/acf/issues/494

# :bug: BUGS / Suggestions for improvement

### Duplicated ACF blocks includes always the same block id
https://github.com/AdvancedCustomFields/acf/issues/301

### Switch to edit mode fields inherit editor styles
https://github.com/AdvancedCustomFields/acf/issues/492

### Case sensitive Issue on <clipPath> / <clippath> and InnerBlocks
https://github.com/AdvancedCustomFields/acf/issues/514

I invite everyone to take an active part in this discussion: @AaronRutley @acf-extended @aircraft @jasonbahl @wpmark @JiveDig @simonseddon @nick6352683 @Log1x @billerickson @polevaultweb

If you know other users who work a lot with ACF, feel free to invite them for discussion :link:. If you have further inquiries or significant bug reports that were not mentioned, you can link them here.

@deliciousbrains I hope this topic is well received and can clarify open questions for many ACF users.

**Comment by kanlukasz** [comment]
It's good to see that someone has already created this post.
_(Maybe it should be pinned?)_

For me as a developer with a lot of `WP` with `ACF` instances it is very important to know what we can expect from the DB team and what your roadmap will look like

**Comment by mattgrshaw** [comment]
Hey @CreativeDive, thanks for raising this!

So without getting too in-depth on each of those issues, there are a few broader questions here that are worth addressing here.

> I wonder how @deliciousbrains will interact with user inquiries in the future?

We've always appreciated bug reports, feature requests, etc and we'll definitely continue to consider these when planning releases and building roadmaps. With ACF, I feel that this is even more important than with our other plugins because of the massive amount of users and the huge variety of ways that ACF is used.

As you might expect, the past few weeks have been busy for us in terms of ramping up so we might have been a bit quieter on GitHub than usual.

> As a one man band, progress with increasing changes in WordPress was associated with long waiting times. Which is completely logical to me. With @deliciousbrains and more man power, maybe that will change in the future?

Yep, with more people to throw at the project, the release cadence will be different. Once we're really in the swing of things, we anticipate getting a major release out around every 6 weeks or so, with important bugfix releases as needed.

And having multiple devs on the project means that we'll be able to build new features while also testing the latest changes happening in WordPress core and adding support/compatibility for that side of things as well.

Regarding the issues you've pointed out, a lot of these are definitely on our radar and some are currently in development as well. We don't have an ETA on when all of these issues will be addressed, but I can say that investigating V2 of the blocks API and addressing some of these block-related issues will be one of our priorities over the coming weeks.

If we have any questions regarding issues you've raised or need clarification/feedback on something, we'll definitely let you know 👍 And likewise, feel free to reach out if there is anything we can help with in the meantime.

**Comment by CreativeDive** [comment]
@mattgrshaw Thanks for response and nice to now @deliciousbrains will continue the work like Elliots vision.

I think the possibility to support inner blocks for the repeater field is an important thing we have to discuss. At this time, I think the writing flow of the block editor is a big pain point here.

If we use ACF inner blocks, we can allow blocks like the "Heading" or "Paragraph" block instead of ACF "Heading" or "Text" fields in the block editor sidebar. This is really cool, because we can support the writing flow of the block editor and the user can change text directly inside the editor view.

If we use repeater fields, this is breaking this writing flow.

On the other hand, I don't know if inner block support for repeater fields is a feature @deliciousbrains can make true?

Can @deliciousbrains say more about whether or not this possibility will come true in the future?

**Comment by acf-extended** [comment]
Hello everyone,

Thanks for mentioning me on this topic! As a developer of a plugin that _heavily_ rely on ACF code base, I must say that the recent acquisition of ACF by Delicious Brains is quite exciting! I agree with everything Elliot's said in the announcement blog post and I think this new chapter really brings new perspectives to the plugin.

Here are few feedbacks and expectations I would like to share with you guys. I'll try to make it concise and highlight few key points:

### Philosophy

**Seamless Integration**
No fancy UI, flashy buttons or notices. What we love about ACF is that fields and UI just blend in the WordPress admin, like if it was part of the core. Simple menu, seamless styles and a touch of JS... The recipe for a happy WordPress user! I really hope the new team in charge will keep that motto.

**Work from the UI or from the code**
Being able to configure ACF from the admin for a quick & easy setup, or register field groups from the code for programmatic usage, is such a great capability. I think this should be the credo for all future features, so everyone can have fun with ACF. From the most simple blog to the most complex job board, we should not leave anyone behind.

**Focused on productivity**
From the Flexible Content to the recent Block Types feature, ACF always has been a pioneer in innovation, a toolbox that resolves real life problems. Some plugin developers may be disconnected from those problems, since they are focused on the tool, not the final website. So I hope the team will keep listenning to users to get real life feedbacks.

### Improvements

**Remove `_field_key` Reference Meta**

Yes I know, it's an old topic, but this would be a very welcome overhaul of the ACF code base. Being able to use the same name for different fields in different field groups really makes things easier for users, but the reference meta logic starts becoming quite old. We need to get rid of it. This is also one of the oldest ACF shortcoming: it saves 2 meta for each field.

**Ajax Field Conditional Logic**

This one could be a game changer, as it would let users conditionally display fields based on dynamic values such as screen locations, user capability or site-wide field values, directly from the UI.

**Block Type: Ajax Value Validation**

I'm not much a Gutenberg/Block Typer user, but I think the biggest blocker which prevent agencies to fully embrace Block Types (and by extension, Gutenberg) is the Ajax Value Validation which is still missing. Allowing a client to enter random values, without being able to validate them is just a big _nope_ for most of us.

**Javascript Documentation**

After spending countless sleepless nights working with the ACF Javascript API, I must say it is one of the most underrated area of the plugin. It is such an amazing piece of software... smart, optimized and extensible!

It's really too bad that the current documentation is just an introduction to some basic concepts. Community and developers would really benefit from a fully-fleshed documentation. There's just so much to say about it!

There's other areas of the code base that could be improved, like the field groups render vs screen filters logic, hooks enhancements with more context, REST API support etc... But I will leave that for future topics :)

Thanks again!

Have a nice day.

Regards.

**Comment by CreativeDive** [comment]
@mattgrshaw We miss the response on open issues here on Github :-) We were used to getting quick feedback from Elliot. Some issues have been unanswered for weeks.

**Comment by polevaultweb** [comment]
Hey @CreativeDive and everyone,

Thanks for all your feedback and suggestions, we hear you 😃

We're busy at work over at Delicious Brains on our first big release, 5.10, which will bring a few features people have been requesting for a while now. We've just released a RC version of 5.10 that is available to download from the account area on advancedcustomfields.com 

Whilst we may appear quiet here on GitHub, it's important to remember the vast majority of our bug reports come from our support mailbox. Many of the issues fixed in our first 3 releases were reported this way.

Closing this issue as we'll be focusing on the individual issue threads

Thanks again 🙌
