### ISSUE TITLE
acf-block-preview missing

### ISSUE THREAD

**Issue by kevinpoot** [AdvancedCustomFields/acf#552]
ACF version: 5.10.x pro

Hi,
Since version 5.10.x the class `.acf-block-preview` that used to wrap a ACF GB block has been removed or it's not working correctly, this results in a situation where there is no more difference in the DOM between viewing a block and editing it. (I use auto mode). In the changelog there is a mention about this: `Fix - Don't render the "acf-block-preview" div when preloading blocks in edit mode`. Is there any way to disable the preloading feature? Or maybe add a class for previewing a block?

Having a class specifically for previewing a block is quite essential, i hope this can be fixed soon.

Thanks in advance.

**Comment by lgladdy** [comment]
Hey @kevinpoot,

Since 5.10, we were incorrectly wrapping a block in edit mode in a `.acf-block-preview` tag. This class is only supposed to be for when we're in preview mode. We fixed this in 5.10.2, and it should now behave like it did in 5.9.x.

If you're previewing a block, the `.acf-block-preview` wrapper should still be applied. Could you share a screenshot of the DOM if this isn't the case and we'll look into it?

We might also need to see your template and block definition to reproduce any issues here - feel free to attach those to the support ticket you opened if necessary!

**Comment by kevinpoot** [comment]
Hi @lgladdy,

Thanks for your reply!

I have the screenshots for you, as you can see in version 5.10.2, the `acf-block-preview` is missing.

**ACF 5.10.2 (preview mode):**

![5 10 2-preview](https://user-images.githubusercontent.com/36954637/133070360-c14377f2-a6bf-49f7-9cfb-9d653d1c6057.png)

**ACF 5.9.9 (preview mode):**

![5 9 9-preview](https://user-images.githubusercontent.com/36954637/133070513-92916d9b-e594-416c-866b-3c0c7072d1d8.png)

**ACF 5.10.2 (edit mode):**

![5 10 2-edit](https://user-images.githubusercontent.com/36954637/133070401-9bf2fdc5-e239-480e-aa90-9b21dd0151a9.png)

**ACF 5.9.9 (edit mode):**

![5 9 9-edit](https://user-images.githubusercontent.com/36954637/133070647-d68a28ec-69d1-4d61-a678-0bc370f1c9b7.png)

**Comment by lgladdy** [comment]
Thanks @kevinpoot,

This is interesting! I'll do some debugging here. I'm wondering if this is specific to `auto` being the mode. If you set it to preview, does that correctly add the wrapper for your block?

**Comment by kevinpoot** [comment]
Yeah in preview mode it does add the wrapper! So i guess there is currently a bug in auto mode.

**Comment by confizz** [comment]
This modification in pro/blocks.php:360 fixed this issue for me:

`if ( 'preview' === $mode && $is_preview ) {`
to
`if ( ('preview' === $mode || 'auto' === $mode) && $is_preview ) {`

**Comment by kevinpoot** [comment]
hi @lgladdy! any news on this issue?

**Comment by lgladdy** [comment]
Hey @kevinpoot,

Yeh! We've got a fix planned for this in our next release - but it is a few weeks away yet. If you want to make the modification @confizz suggested manually for now, hopefully that will tide you over! I think our fix will be very similar to that one.

**Comment by mattgrshaw** [comment]
@kevinpoot @kandreas @confizz

Thanks for your patience on this. We've pushed out a release candidate that has this issue fixed up, which can be downloaded from the "[My Account](https://www.advancedcustomfields.com/my-account/)" section of our site for pro, or if using the free version, attached here.

[advanced-custom-fields-5.11-RC1.zip](https://github.com/AdvancedCustomFields/acf/files/7464153/advanced-custom-fields-5.11-RC1.zip)


If you're interested in helping test out the fix, we'd recommend setting that up on a dev/staging site if possible since we're still testing that release on our end as well.

If all goes well, we're anticipating on releasing the official version sometime next week.
