### ISSUE TITLE
get_field returns null after upgrading to v5.11

### ISSUE THREAD

**Issue by alenaksu** [AdvancedCustomFields/acf#570]
After upgrading from version 5.10.2 to 5.11 `get_field` started to return `null` for every field.
I tried both calling it in a loop or by passing the post id to the function.

The information on the database are correctly stored, in fact I'm able to retrieve them by using `get_post_field`.

**Comment by mattgrshaw** [comment]
Hi @alenaksu,

Sorry to hear you ran into trouble with the update. Are the fields/field groups you're having trouble with registered via PHP by any chance? i.e. with `acf_add_local_field_group()` / `acf_add_local_field()`?

If so, could you please share the code you're using the register them?

**Comment by alenaksu** [comment]
hi @mattgrshaw 
nope, I created them in the admin panel. 
Does the local json file help in understanding the issue?

**Comment by mattgrshaw** [comment]
Yep, that would be helpful thanks.

If you could also share an example of the code where you're using `get_field()` that would be great.

**Comment by arjendejong12** [comment]
I've experienced the same problems. Debugging led me to [the following](https://github.com/AdvancedCustomFields/acf/commit/cf20fa18234c87632e1182b52eff73d77b19e3a3#diff-bf32fa5193cfaecc16ae4db1285b305969760958b55b83d23c3e3ecebc3ff30c) change.
What caused my problems was that I was registering field groups with `acf_add_local_field_group` too late, in the `init` hook at priority `12`, while I should've done it outside any hooks.

 When retrieving a field value, ACF couldn't find the field object so it created [a dummy field](https://github.com/AdvancedCustomFields/acf/blob/cf20fa18234c87632e1182b52eff73d77b19e3a3/includes/api/api-template.php#L28). It then tried to find the field object by name (see new change), but because it didn't exist in the database, and couldn't be found in local fields (because they were registered too late), it returned `null` for the value.

**Comment by mattgrshaw** [comment]
@arjendejong12 Sorry to hear you ran into this, but glad to hear you got it resolved!

The problem stems from a security update to `acf_get_value()` (which is used by `get_field()`).

`get_field()` now requires the field to exist in order to get a value for it, where before it was a bit more relaxed. This isn't an issue most of the time, but can be an issue if the field is registered late in the request cycle. 

We recommend registering any PHP fields in your theme's functions.php or in the `acf/init` hook:
https://www.advancedcustomfields.com/resources/register-fields-via-php/
https://www.advancedcustomfields.com/resources/acf-init/

**Comment by alenaksu** [comment]
this gist contains the json with a small example
https://gist.github.com/alenaksu/455177665e03f120cc39f0a468bb0a09

**Comment by pabois** [comment]
Same problem here.
The get_field method works ok in the front theme, but return null when used in back office.

**Comment by mattgrshaw** [comment]
@alenaksu Thanks for providing that export and code sample. I tested out `get_field()` with that field group and field, and unfortunately was unable to replicate the problem. Can you please confirm how that code is being ran - i.e. is it in your theme template files, a custom plugin, etc.?

**Comment by mattgrshaw** [comment]
@pabois Sorry to hear you ran into this as well. Can you please also share some sample code where things are going wrong for you as well? If you'd rather troubleshoot via email, feel free to send an email to support@advancedcustomfields.com so we can dig into it further.

**Comment by pabois** [comment]
Hi @mattgrshaw!
I just display a custom page on my wordpress admin, and in the code of the custom page I have a call like ```get_field('my_field_id', $_GET['id'])```
This now returns null where it was ok before.
When I declare manually my fields in the custom page, using ```acf_add_local_field_group``` the value of get_field is ok.

**Comment by lgladdy** [comment]
@pabois Hey, could you drop us a email to the address above with some more details of your setup and code? Specifically, how you've registered the fields, and how you're outputting the admin page.

It sounds like that output is happening before the fields get registered.

**Comment by alenaksu** [comment]
@mattgrshaw I found out that for some reason the hidden meta fields used by ACF (the ones that starts with underscore) are empty on my database. I tried to update the post manually from the admin panel and after that the hidden meta fields were populated with something like`field_603d80dee9a7c` and started to work again. 

To give you more context, I'm populating the fields programmatically by calling `update_field`.

Hope this helps.

**Comment by thomasmb** [comment]
> `get_field()` now requires the field to exist in order to get a value for it

I've actually seen this cause issues already and it is kind of a big change imho. I understand the choice, and though I use `get_field` for acf specific fields, I am met with projects on a regular bases where this isn't exclusively the case. Also I'm not certain how much of a problem it really was if people did use get_field as a shorthand for `get_post_meta`.

But there will certainly be plenty of sites where this constitutes a breaking change.

**Comment by thomasmb** [comment]
@lgladdy could it be an option to create a define constant that would continue to allow using get_field as it was previously (where it would double as a shorthand for get_post_meta) - mainly to avoid breaking sites that have this implemented until they are refactored? Something like ACF_STRICT_MODE_DISABLED?

**Comment by arjendejong12** [comment]
Even though I have fixed my problem as described here earlier, I would still advocate for the solution @thomasmb suggestsas this is a pretty big change.

**Comment by SergiArias** [comment]
I cannot use get_field to retrieve fields from a user anymore in 5.11.1, and I have to use the wp get_user_meta. Is this a breaking change too? Are taxonomies or other types also involved?

**Comment by lgladdy** [comment]
Hey everyone,

We've made some changes in last week's ACF 5.11.2 release which should help mitigate the majority of issues you've been experiencing in ACF 5.11 and 5.11.1.

You can view full details in the [changelog](https://www.advancedcustomfields.com/changelog/) and the [acf field functions documentation](https://www.advancedcustomfields.com/resources/acf-field-functions/).

If you're still having issues, please drop us an email to support@advancedcustomfields.com and we'll pick it up there!

**Comment by pabois** [comment]
Indeed, I've reverted my fixes and all is working as before.

Thanks!
