### ISSUE TITLE
Shortcode "acf" returns nothing for guest user performing AJAX requests since version 5.10

### ISSUE THREAD

**Issue by YushkinaS** [AdvancedCustomFields/acf#589]
On my website, I have a template that's loaded by AJAX. This is enabled for any visitor. This template displays any content with any shortcodes. I used "acf" shortcode, and it worked fine. But after updating the ACF plugin to 5.10, I found that the shortcode returns an empty string. I looked into the code, and found this in acf_shortcode function:

```
// Mitigate issue where some AJAX requests can return ACF field data.
    if ( wp_doing_ajax() && ! current_user_can( 'edit_posts' ) ) {
        return;
    }
```

This code seems to break a page since parts of a page’ content, which are supposed to be added by "acf" shortcode, are just empty for unregistered users.

**Comment by lgladdy** [comment]
@YushkinaS This is by design I'm afraid. Allowing guest users to access the ACF shortcode is a potentially significant security risk, as it could allow access to confidential data.

Since ACF 5.11.4, there is [a filter](https://www.advancedcustomfields.com/resources/acf-ajax-shortcode_capability/) which allows you to modify the role required for the shortcode to execute, but it's very important if you use that filter to lower the capability, you are doing your own security checks to ensure the data being accessed if safe.
