### ISSUE TITLE
Image array returns only ID in REST endpoint

### ISSUE THREAD

**Issue by gablittledevshop** [AdvancedCustomFields/acf#594]
We recently updated the ACF plugin to the latest Version 5.11.4, and noticed when an Image field has Return Format Image Array, it doesn't return an object in the rest endpoint, it only returns the id. Here's a snippet of the output:

```
"acf": {
"category": 8,
"date": "2021-12-21 17:40:15",
"image": 214,
"summary": "testtest",
"description": "testtest",
"link": "",
"text": "sdfasfdwerwe rwer qwerwer"
},
```

This may or may not be related, but after the update, the `image` field was absent from the rest endpoint entirely. To test I renamed the field to `image2`, where it showed up again, so I renamed it back to `image`.

**Comment by johnolek** [comment]
We just ran into this issue ourselves. We were previously manually appending `act` fields to REST API responses using `get_fields`, which does respect the `return_format` of an image.

You can control this behavior in two ways: 

1. Using the `acf_format` parameter in the REST API call with a value of `standard`. For example, instead of `domain.com/wp-json/v2/pages?slug=test` you would hit `domain.com/wp-json/v2/pages?slug=test&acf_format=standard`.
2. Adding a filter to `acf/settings/rest_api_format` to return a value of `standard`.
```php
add_filter('acf/settings/rest_api_format', function() {
    return 'standard';
});
```

ACF uses a function  `acf_format_value_for_rest` to determine the REST formatting of a field's value.

```php
function acf_format_value_for_rest( $value, $post_id, $field, $format = 'light' ) {
	if ( $format === 'standard' ) {
		$value_formatted = acf_format_value( $value, $post_id, $field );

	} else {
		$type            = acf_get_field_type( $field['type'] );
		$value_formatted = $type->format_value_for_rest( $value, $post_id, $field );
	}

	/**
	 * Filter the formatted value for a given field.
	 *
	 * @param mixed      $value_formatted The formatted value.
	 * @param string|int $post_id The post ID of the current object.
	 * @param array      $field The field array.
	 * @param mixed      $value The raw/unformatted value.
	 * @param string     $format The format applied to the field value.
	 */
	return apply_filters( 'acf/rest/format_value_for_rest', $value_formatted, $post_id, $field, $value, $format );
}
```

You can see where it's getting its `$format` value in `class-acf-rest-api.php` inside `load_fields`. That value must be `standard` to get the full array of image data.

```php
...
// Format the field value according to the request params.
$format = $request->get_param( 'acf_format' ) ?: acf_get_setting( 'rest_api_format' );
$value  = acf_format_value_for_rest( $value, $post_id, $field, $format );
...
```

I found this all pretty unexpected for a minor version update, but I also recognize that the way we were adding the `act` property to our REST responses isn't all that typical.

We were previously using functionality taken from https://wordpress.org/plugins/acf-to-rest-api/, so anyone using the "ACF to REST API" plugin might be experiencing this issue depending on their field definitions.

**Comment by gablittledevshop** [comment]
Adding the filter in our custom plugin worked for us.

```
add_filter('acf/settings/rest_api_format', function() {
    return 'standard';
});
```

Thanks!

**Comment by mattgrshaw** [comment]
Sorry for the delay on this one folks.

ACF does return an ID for images by default - this is by design so that the input and output formats match. As noted in this thread, using the `acf/settings/rest_api_format` filter to switch the output format to "standard" will return whatever you have set as the "Return Format" for that field.
