### ISSUE TITLE
Duplicating Columns block with ACF blocks duplicates block ID

### ISSUE THREAD

**Issue by andersnoren** [AdvancedCustomFields/acf#621]
Hi everyone,

I have a columns block with a ACF block in each column saved as a block pattern. Based on [this issue](https://github.com/AdvancedCustomFields/acf/issues/301), I've left the `id` parameter in the markup for the ACF block empty. When the pattern is inserted, IDs are created and everything behaves as expected.

However, if I duplicate the columns block in the pattern (which contains the ACF blocks), the duplicated ACF blocks have the same IDs as the original ACF blocks, causing issues when changing values of radio fields, updating the post etc. I was wondering if anyone else can replicate this issue, or if I've managed to screw something up in the registration of the blocks and/or patterns.

This is the pattern markup:

```
<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:acf/lnob-numbers {"id":"","name":"acf/lnob-numbers","data":{"content_number_prefix":"","_content_number_prefix":"field_621e21a95eff6","content_number":"119-124","_content_number":"field_621e21c55eff7","content_number_suffix":"","_content_number_suffix":"field_621e21d05eff8","content_text":"miljoner människor hamnade i extrem fattigdom under 2020","_content_text":"field_621e21ee5eff9","content":"","_content":"field_621e215961e94","appearance_color_bg":"gg","_appearance_color_bg":"field_621e2508048c7","appearance":"","_appearance":"field_621e24f7048c6"},"align":"","mode":"edit"} /--></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:acf/lnob-numbers {"id":"","name":"acf/lnob-numbers","data":{"content_number_prefix":"","_content_number_prefix":"field_621e21a95eff6","content_number":"60","_content_number":"field_621e21c55eff7","content_number_suffix":" %","_content_number_suffix":"field_621e21d05eff8","content_text":"av dem bor i södra Asien","_content_text":"field_621e21ee5eff9","content":"","_content":"field_621e215961e94","appearance_color_bg":"gg","_appearance_color_bg":"field_621e2508048c7","appearance":"","_appearance":"field_621e24f7048c6"},"align":"","mode":"edit"} /--></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

**Comment by venomgfx** [comment]
Hi,

Not related to Columns per se but I'm also running into blocks having the same `id` after duplicating them. Outside of patterns even, just regular blocks.

In my case I'm registering the blocks using [`acf_register_block_type`](https://www.advancedcustomfields.com/resources/acf_register_block_type/) via PHP. Running WordPress 5.9.1 and ACF Pro 5.12.

**Comment by nick6352683** [comment]
For me it's strictly columns issue. Duplicating or copy/pasting an ACF block INSIDE the core columns block results in identical ID's. I tried the same with the duplication being inside a Group block (to determine if this is somehow an innerblocks issue), and the ID's here are not the same - all good here. I also tested other scenarios, and so far I think the only the duplicate ID issue is happening inside the core Columns.

For now an easy way to avoid this bug is to create and duplicate the blocks outside of the Columns block, and when you have all the blocks ready, just move them inside the Columns.

**Comment by JiveDig** [comment]
There are a few reports and lengthy discussions of this and similar issues already. See https://github.com/AdvancedCustomFields/acf/issues/183, https://github.com/AdvancedCustomFields/acf/issues/605, https://github.com/AdvancedCustomFields/acf/issues/478. They are aware of it but we all certainly hope it gets fixed soon :)

**Comment by lgladdy** [comment]
@andersnoren @nick6352683 A bug was introduced in ACF 5.12 where the duplication detection doesn't take place properly for blocks nested more than 1 level deep (columns > column > acf-block). We'll get this fixed in ACF 5.12.1 in the next week or two - if you drop back to ACF 5.11.4, does that help? I'd like to confirm that's the issue you're having.

**Comment by pjoulot** [comment]
Hello @lgladdy 
I had the same bug, I confirm that reverting to ACF 5.11.4 seems to fix the issue.

**Comment by lgladdy** [comment]
@pjoulot Thanks! We'll get that aspect of this bug fixed ACF 5.12.1, currently targeted for next week.

We're then hoping to run a ACF 5.13 for a few weeks which will remove block IDs altogether. We'll want to get that in your hands in a test state for a while to make sure we're not going to cause any back compat issues.

**Comment by venomgfx** [comment]
> We're then hoping to run a ACF 5.13 for a few weeks which will remove block IDs altogether.

This will definitely break some of my blocks on which I use the ID, but I understand it must be hard to get it right. If IDs go away please make it prominent in the release notes for people relying on them.

**Comment by lgladdy** [comment]
@venomgfx We will - but ideally we will make sure this won't break things for users. How are you using block IDs at the moment that you think will be broken by them being removed? We were intending to generate a pseudo block ID so that `$block['id']` is still present in the template - potentially based on an MD5 hash of the block.

**Comment by venomgfx** [comment]
> @venomgfx We were intending to generate a pseudo block ID so that `$block['id']` is still present in the template

Oh that'd be perfect! I'm using `$block['id']` to build a block name + ID and be able to style specific blocks this way. If `$block['id']` is still available with some kind of unique number that's perfect. MD5 seems ideal. Thanks for working on it!

**Comment by nick6352683** [comment]
I can confirm that v5.12.1 fixed this issue for me - thanks a million for that !

Note: Initially the issue was still showing up after the manual update of the plugin, but after flushing the editor cache (Ctrl + F5 in Chrome while editing), the correct v5.12.1 files were loaded, and duplicating ACF blocks within columns work like a charm again...

**Comment by lgladdy** [comment]
Thanks for the confirmations everyone! Let us know if you're still having this issue after upgrading to ACF 5.12.1, but this should be fixed now.
