### ISSUE TITLE
Warning Deprecated PHP 8.0

### ISSUE THREAD

**Issue by Olwyne** [AdvancedCustomFields/acf#640]
Hi, my website is on PHP 8.0 and I have these warnings :

```
Deprecated: Required parameter $post_id follows optional parameter $meta_tabs in /var/www/html/wp-content/plugins/cbxtakeatourpro/cbxtakeatourpro.php on line 265

Deprecated: Required parameter $field follows optional parameter $i in /var/www/html/wp-content/plugins/acf-repeater/includes/5-7/acf-repeater-field.php on line 739

Deprecated: Required parameter $post_id follows optional parameter $i in /var/www/html/wp-content/plugins/acf-repeater/includes/5-7/acf-repeater-field.php on line 739

Deprecated: Required parameter $field follows optional parameter $i in /var/www/html/wp-content/plugins/acf-repeater/includes/5-7/acf-repeater-field.php on line 805

Deprecated: Required parameter $post_id follows optional parameter $i in /var/www/html/wp-content/plugins/acf-repeater/includes/5-7/acf-repeater-field.php on line 805
```

Plugin version : Version 5.12.2

**Comment by lgladdy** [comment]
@Olwyne Hey, do you have the legacy ACF 4 repeater plugin still installed? You should be safe to disable that, as since ACF 5 the repeater plugin has been part of the main plugin.

**Comment by Olwyne** [comment]
I have all of theses plugins about ACF : 

![image](https://user-images.githubusercontent.com/46401913/163382545-1189a7c7-ed96-43b0-b069-8612c4671618.png)

If I understand well, I need to remove the last one ?
Thanks for your help !

**Comment by Olwyne** [comment]
Everything works fine ! Thanks :+1:

**Comment by tiagorfc** [comment]
Hello,

Since moved to PHP 8, I'm having this warning in our website:
Deprecated: Required parameter $field follows optional parameter $i in /home/agtdev2cm/public_html/projetos/condo_livre/wp-content/plugins/acf-repeater/includes/5-7/acf-repeater-field.php on line 739

I use the Advanced Custom Fields and Advanced Custom Fields: Repeater Field

**Comment by lgladdy** [comment]
@tiagorfc The legacy ACF Repeater Field is no longer updated, and doesn't support on PHP 8 (or ACF 6) I'm afraid.

If you already have an ACF PRO licence, you can upgrade to ACF PRO 5.x or 6.x which included a supported repeater field for PHP 8, otherwise, you can manually edit that file on your install and remove the `= 0` for `$i`

Your function definition should end up looking something like:
`function update_row( $row, $i = 0, $field, $post_id ) {`
