### ISSUE TITLE
BUG: Filter acf/prepare_field/... is no longer working

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#652]
Hey @lgladdy,

I want to use the "`acf/prepare_field/key=field_123abcf`" filter, but it seems this filter is no longer working.

I have a ACF block and I want to hide a field in a specific case. It was mentioned that "acf/prepare_field" is the perfect solution for that: [https://www.advancedcustomfields.com/resources/acf-prepare_field/](https://www.advancedcustomfields.com/resources/acf-prepare_field/)

But absolutely nothing happened by using this filter.

Here the example:

```
if ( ! function_exists( 'wphave_query_list_block_hide_post_per_page' ) ) : 

	function wphave_query_list_block_hide_post_per_page( $field ) {

		error_log(print_r($field,true));	
		
		$parent_field_group = isset( $field['parent'] ) ? $field['parent'] : '';
	
		if( $parent_field_group === 'group_5bf07a47f00d6' ) {
			return false;
		}
		
		return $field;
		
	}

endif;

add_filter('acf/prepare_field/key=field_57fd1127dfc5e', 'wphave_query_list_block_hide_post_per_page');
```

The "`error_log(print_r($field,true));`" is not fired if I select a ACF block which contains this field.

**Comment by mattgrshaw** [comment]
Hi @CreativeDive,

That's a strange one. I just tested the `acf/prepare_field/key=` filter and was able to remove the field from the form on blocks as well as other UI locations.

If the `error_log()` call isn't firing, you may want to double check that the field key is correct in the `add_filter()` call, or perhaps try using the field name to see if it works that way.

Otherwise if you're sure that everything is correct, could you please attach a JSON export of any field groups needed to replicate and I can see if I can spot the issue on my end?

**Comment by CreativeDive** [comment]
@mattgrshaw thank you for response and sorry for the delay. At the meanwhile I have tested the great new features from ACF 6.0.0-alpha1 version.

I have tested this again in other cases and can confirm the filter is working as expected. Sorry for confusing, this was my mistake. It seems something was not right in my first test case.
