### ISSUE TITLE
Support status

### ISSUE THREAD

**Issue by romainmenke** [AdvancedCustomFields/acf#683]
Hi all!

Can we get an update of the current state of ACF?
Seems that all the work is going towards 6.0 but this update is not at all compatible with existing projects.

For how long will 5.x be supported going forward?
It's been a long time since non-security bugs were fixed.

**Comment by lgladdy** [comment]
Hey @romainmenke, ACF 6.0 should be compatible with all existing projects and sites. None of the changes should be breaking, so please let us know if you find any :)

**Comment by romainmenke** [comment]
If it is compatible it would not be 6.x :D
Please keep it all clear for users.

https://www.advancedcustomfields.com/blog/acf-pro-6-0-beta-1/

> Block ID Removal
>
>This release of ACF will remove saved block IDs from ACF Blocks. This affects all versions of ACF Blocks and means you can easily copy and paste blocks, simplify your post type templates or block patterns, or duplicate blocks without having any issues where block IDs clash.
>
>We’re hoping this change is transparent to users, and any existing blocks will have their block IDs removed the first time they’re edited after installing ACF 6.0. We’ll still generate a $block['id'] for your templates as we know some users use that for element IDs, but the format of those IDs will change, and may be duplicated if you have multiple blocks on the same page with the exact same data (similar to how block IDs are the same inside a query loop block now)

This is clearly breaking...

**Comment by lgladdy** [comment]
We don't believe this is breaking, as we maintain backwards compatibility with the automated block ID generation. All of our tests on production websites show no breaking changes with upgrades to 6.0.

**Comment by romainmenke** [comment]
> All of our tests on production websites show no breaking changes with upgrades to 6.0.

That is not how backwards compat works :/
It is not because you do not have a failing test after a change that everything is ok...

**Comment by lgladdy** [comment]
We've run the block ID changes in a public developer preview here on GitHub for the [last few months](https://github.com/AdvancedCustomFields/acf/issues/654) so we could ensure that, in the real world, there were no breaking changes for users.

If you find an issue with 6.0.0-beta1, please do open an issue, and we'll be more than happy to get it fixed before release! Cheers :)

**Comment by romainmenke** [comment]
Wait, whut, ...
Why is this closed?
The original question was completely ignored....

Can you just clarify the support status of 5.x?
I've been patiently waiting for a few months for a bug fix of mine to be merged and released.

I understand and respect we all have busy schedules and that things take time.
(check the projects I maintain, I am not new to all this)

But please do not cause confusion with an announcement of a next major, then state that it is non-breaking and close the issue.

-----

What is the support status of 5.x?

**Comment by polevaultweb** [comment]
Hi @romainmenke, product manager for ACF here.

ACF 5.x is currently supported. 6.0 will be our next major version after 5.12 in the same way [WordPress approaches versioning](https://make.wordpress.org/core/handbook/about/release-cycle/version-numbering/), with the focus on new features rather than breaking changes.

Can you let me know what bug you are referring to?

We use GitHub issues for reporting bugs as it comes directly to us developers, so we close issues that aren't bugs.

For support, you can use either the forum at https://support.advancedcustomfields.com/ or drop an email to our support team at [support@advancedcustomfields.com](mailto:support@advancedcustomfields.com). Feel free to follow up on your support ticket and I'll get that looked at.

**Comment by romainmenke** [comment]
https://github.com/AdvancedCustomFields/acf/pull/662

**Comment by romainmenke** [comment]
But anyone who recently opened an issue or a pull request might have the same feeling and questions as me and will likely be wanting to see their stuff resolved.

**Comment by romainmenke** [comment]
As I understand the respons on this issue 5.x is no longer supported in any way :/

**Comment by edavies-ddc** [comment]
> We don't believe this is breaking, as we maintain backwards compatibility with the automated block ID generation. All of our tests on production websites show no breaking changes with upgrades to 6.0.

This is definitely a breaking change depending on how blocks are used. For example I use them on the frontend and then send them via ajax and compare them to the block ID in the editor to compare settings and validate data. Now the ID is only available on the frontend. Previously. I could use parse_blocks and compare the ['attrs']['id'] attribute in ajax and find the block I needed to compare. I can no longer do this in 6.0.

**Comment by lgladdy** [comment]
@edavies-ddc You can generate the same ID in the backend too if you need to as well, we use it for matching preloads - we just use the WordPress's clientID for display for performance.

I'm a bit confused by your use case though, I don't understand what you mean by frontend and send them via AJAX? If you're using parse_blocks in your AJAX call, then $block['id'] will be the same as what it is in the front-end so will continue to match... Only in the block editor do we use the WordPress provided clientID - and even then you could get the same ID if you need; we generate it in order to match preloads.

**Comment by edavies-ddc** [comment]
@lgladdy  - I understand I can use some work arounds and generate IDs myself which is what I'm working on doing now after reading through all the change logs etc, however me needing to do this is because 6.0 will break my existing code. Consider this use case:

I have ACF fields for a custom 'contact us' block. This accepts fields like 'subject', 'to email', 'after success message'. For subject/after success message it doesn't really matter I can output those in the frontend. However the 'to email' is sensitive and I don't want it exposed. When someone submits the contact form on the frontend it submits an ajax request to admin-ajax and passes the Page ID you're on and the Block ID. In the admin-ajax request I use parse_blocks and loop through each block, comparing the ['attrs']['id'] attribute until I find the matching ID and get the 'to email' from the settings.

In ACF 5.12.3 using parse_blocks there's an 'ID' attribute which matches the one on the frontend. In ACF 6.0 the blockId seems to be only available on the frontend, I'm assuming it's generated on the fly and no longer stored as an attribute on the content. 

So understanding there's likely a way to duplicate the way you're generating these IDs, the situation seems to remain that in 5.12.3 the ID attribute exists on the block and in 6.0 it does not. I understand the desire to make these IDs unique. It's my recommendation in order to maintain backwards compatibility that you continue to keep the ID attribute on the block, but use the same new frontend hash technique on this ID.

**Comment by romainmenke** [comment]
I remain to be confused by the : "it's not breaking but you might need to make a change for things to work as they did before".

It would be much simpler and clearer if 6.0 was clearly communicated as a version with breaking changes.

**Comment by lgladdy** [comment]
@edavies-ddc Unfortunately, we can't continue to keep the ID attribute on the block - removing them has been the number one feature request for ACF Block users for some time now. WordPress changes in recent versions mean features like block patterns and styles, and things like custom post block templates all have issues with ACF Blocks while they still have block IDs.

The number of people who will be affected by this change is small, and the number of people who will benefit from the ability to use the new WordPress features is an ever increasing number - we'll make sure our release documentation gives as many examples of workaround code to make sure IDs do still exist.

All our blog posts regarding the release have stated the vast majority of users won't need any code changes, and we'll make sure we document as many examples as we can for those who will need to make changes.

**Comment by edavies-ddc** [comment]
You definitely could keep it on there, but it'd be harder to do that simply remove it. I'm going to implement a work-around where I use the pre_save_block and put it back because I need it. You could do the same and when people copy/paste you could leverage some javascript to change it on the fly or something. As Elliot indicated in this issue:[ issue   ](https://github.com/AdvancedCustomFields/acf/issues/320#issuecomment-646424734) it should be possible, though it may be hard. Perhaps the number of people affected will be small, I'm not privy to the internal feature requests. But to position the change as non-breaking is respectfully, disingenuous. The block ID has not been a problem for me with block patterns, reusable blocks, or copy/pasting blocks thus far so not sure what issues other people are running into with them.
