### ISSUE TITLE
Consider making IDs unique on 6.0.0

### ISSUE THREAD

**Issue by Antonio-Laguna** [AdvancedCustomFields/acf#684]
From this comment https://github.com/AdvancedCustomFields/acf/issues/683#issuecomment-1213307122 it looks like the following isn't considered breaking:

>We’ll still generate a $block['id'] for your templates as we know some users use that for element IDs, but the format of those IDs will change, and **may be duplicated** if you have multiple blocks on the same page with the exact same data (similar to how block IDs are the same inside a query loop block now)

(emphasis mine)

Repeated ids on a page is invalid HTML markup and also it could, inadvertently, create issues given that you could have programatically given a selector that's expected to be unique but it isn't

![image](https://user-images.githubusercontent.com/946645/184490404-3c973ed8-90fc-446c-8695-5b0bc18ea11f.png)

**Comment by lgladdy** [comment]
It's already possible for IDs to not be unique in ACF 5.x - they've never been documented as unique, and due to recent WordPress features, it's become even more likely that duplicates would take place.

The conditions that would trigger duplicate block IDs have changed in ACF 6.0, but it is not a new thing that they exist.

We'll make sure we document methods of adding unique IDs to blocks in our release documentation that will apply to all version of ACF Blocks for those who need it.

**Comment by lgladdy** [comment]
Closing this issue as we'll cover this off in documentation, and better explain this isn't really a change in ACF 6!
