### ISSUE TITLE
Image field keeps returning int or bool

### ISSUE THREAD

**Issue by kasparra** [AdvancedCustomFields/acf#781]
I had a lot troubles lately when copying an image field or importing image fields, they keep returning int or bool. I managed to fix a couple of times by deleting the field and changing the return format back and forth.

**Comment by lgladdy** [comment]
Hey @kasparra. This is likely expected behaviour if you don't also copy the ACF field key meta value (that's the one with the `meta_key` beginning with an underscore, so if your field is named `image` that would be `_image`, or use our function `update_field` to handle the import.

If you just set the `post_meta` value to the image ID, ACF won't be able to understand it's a valid ACF field and so won't process it to your requested return format.
