### ISSUE TITLE
How do i get rid of the .acf-innerblocks-container div wrapper for  InnerBlocks?

### ISSUE THREAD

**Issue by rexwreyes** [AdvancedCustomFields/acf#783]
I am trying to use InnerBlocks in my ACF Block.  When i do, however the front end ends up with a wrapping div of all the innerblocks that breaks some functionality (all the elements need a specific class for their wrapper...and NOT .acf-innerblocks-container).  Can i just get rid of this somehow (and why add it in the 1st place)?

**Comment by lgladdy** [comment]
We add it because we're required to add a container in the backend, and matching markup between backend and frontend is important for developers with their CSS targeting.

You can find more information, including how to turn this off on the frontend only, in our documentation: https://www.advancedcustomfields.com/resources/whats-new-with-acf-blocks-in-acf-6/#block-versioning

**Comment by rexwreyes** [comment]
Ok so in looking at the code here /advanced-custom-fields-pro/pro/blocks.php i see i should be able to turn it off or assign a class

**Comment by rexwreyes** [comment]
thanks for the reply @lgladdy .  the filter is what i needed.

**Comment by lgladdy** [comment]
@rexwreyes No worries! Glad it works for you! As you can imagine, WordPress's React components requires a container in order to support things like drag and drop in the backend, and we had many users struggling that the backend markup behaved differently to the frontend so standardised that in ACF 6.0 to make sure by default the markup was the same between the two.
