### ISSUE TITLE
WordPress 6.2.1 Update Disabled ACF Field Groups

### ISSUE THREAD

**Issue by the-swensonator** [AdvancedCustomFields/acf#833]
Hi there, 

Our custom field groups are no longer populating as blocks since the WP 6.2.1 update. Any work around or help to get these activated again? 

![ACF - Field Groups](https://github.com/AdvancedCustomFields/acf/assets/133990305/9a3e8259-8534-47d7-9a45-fe41635b0515)
![Page - ACF Blocks](https://github.com/AdvancedCustomFields/acf/assets/133990305/75a7d108-a165-4431-92df-179fb5824a99)

**Comment by lgladdy** [comment]
Hey there,

Please contact support@advancedcustomfields.com for help with this one. We use GitHub for more technical bug reports rather than general support or issues.

We've not seen any issues generally with WordPress 6.2.1 and blocks, so this is something specific to your install or setup I'm afraid - and our support team can work with you to try and figure out what's up!

Thanks,
Liam
