### ISSUE TITLE
Unable to update to 6.2.0

### ISSUE THREAD

**Issue by darren-strategiq** [AdvancedCustomFields/acf#863]
I have noticed that on some sites, we are unable to update to version 6.2.0. All of our sites are hosted on WPEngine and the issue seems to be present on a staging environment where production is fine.

The issue is that the plugin reports an update but doesn't display an update button. If I try and update it by checking the box to perform a bulk upgrade, it fails saying the package could not be found.

Most of our staging environments are copies of production and meet the new minimum requirements as mentioned in the 6.2.0 changelog (WP >= 5.8 and PHP >= 7.0)

For context, the license key is correctly set and is active, the staging site in question is running WordPress 6.2.2 with PHP 7.4. The production version of this site is using the same WP and PHP version and has no issues in allowing me to update ACF.

Any advice would be appreciated.

<img width="1088" alt="Screenshot 2023-08-23 at 12 02 44" src="https://github.com/AdvancedCustomFields/acf/assets/130446111/8dd95ae8-65ab-4c4b-a095-990500eff305">

**Comment by lgladdy** [comment]
Hey @darren-strategiq,

Could you please drop us an email to support@advancedcustomfields.com so we can work through this with you?

If you're syncing from production got staging while an update is available, it's possible this error can happen because the production site URL and licence is trying to be applied to the staging site, but we can work with you to get a login and get this sorted!

Cheers,
Liam

**Comment by darren-strategiq** [comment]
This has now been resolved with help from @lgladdy. To summarise, this issue is due to having Object Cache enabled in WPEngine which interferes with the `update_plugins` transient. Turning this off resolved our issue after clearing the caches.
