### ISSUE TITLE
Repeater field type with pagination

### ISSUE THREAD

**Issue by boobika** [AdvancedCustomFields/acf#920]
**Describe the bug**
I would like to use pagination with the Repeater field type, but I'm encountering an error that occurs when editing the page.
Tested on two WP installations.

**To Reproduce**
1. The repeater field has pagination enabled.
2. It contains Image, Text, and URL field types.
3. In the administration, I fill in the repeating items several times.
4. When I reopen the administration, further editing such as editing images is almost impossible. Either the images cannot be deleted, or other images cannot be saved...

**Expected behavior**
Editing repeating items works even with pagination enabled.

**Version Information:**
 - WordPress Version 6.5.5
 - PHP Version 8.1.25
 - ACF PRO 6.2.9
 - Browser chrome 126

**Comment by lgladdy** [comment]
Hey @boobika,

Unfortunately we are not able to provide support via GitHub issues. Please contact our support team at support@advancedcustomfields.com.

As detailed in the template when you opened the issue, GitHub issues are only for detailed bug reports containing details of the ACF code base where the bug is, which we can directly create an internal ticket without needing to do any research.

Our support team will be able to work with you to confirm the bug and get this raised up to the development team if they confirm it's a bug in the plugin.

Thanks,
Liam
