### ISSUE TITLE
Ampersands in Text Area fields produce warnings

### ISSUE THREAD

**Issue by ViliusS** [AdvancedCustomFields/acf#922]
**Describe the bug**
I have a simple page with Text Area ACF field. Every time I write content which contains ampersand (&) in it (using WYSIWYG editor), it produces the following warning:
`ACF now automatically escapes unsafe HTML when rendered by the_field or the ACF shortcode. We've detected the output of some of your fields has been modified by this change, but this may not be a breaking change.`

I've read https://www.advancedcustomfields.com/blog/acf-6-2-5-security-release/ but from what I understand Text Area ACF field should encode unsafe text by default, including ampersands. However, I see that in database it's still not converted to &amp;.

**To Reproduce**
1. Create a field group.
2. Create Text Area ACF field.
3. Add that field to a page and output content with `the_field()`.
4. Write text `test & test` in the field on a page.
5. Open or preview a page as your external clients would do it.
6. Check WP admin panel for the warning.

**Expected behavior**
WYSIWYG editor should encode ampersands in Text Area fields and ACF should not complain about the output.

**Version Information:**
 - WordPress Version 6.5.5 and 6.6
 - PHP Version 7.3.33
 - ACF Free 6.3.4
 - MS Edge 126

**Additional context**
ACF was upgraded from 5.x to 6.3.4, but I have cleared and reentered content in the fields in question.

**Comment by lgladdy** [comment]
Hey @ViliusS,

This isn't a bug, but rather an expected behaviour of our light processing when we detect changes. We noted this in the release notes: https://www.advancedcustomfields.com/blog/acf-6-2-5-security-release/#detection-and-notice-information

> Any detected modification will trigger the log, but it may not necessarily be a breaking change. For example, & become &amp; when escaped. This would be detected as a modification, but is unlikely to be a problem as it will still be rendered normally in the browser. In these cases you do not need to make any code changes, instead you can leave the upcoming automatic escaping to work correctly.

ACF is doing the escaping on output, rather than on save, so users who don't want any escaping can use `get_field` to get the non-encoded version.

You can safely ignore these warnings, of if you're happy the site still works, use the new options on the notification to disable the message forever. The notification will be disabled by default in ACF 6.4 later this year.

Thanks,
Liam

**Comment by ViliusS** [comment]
But if it doesn't do escaping on saving + it doesn't do escaping on output (at least in my case because I still see simple & when viewing HTML code on a website), the bug is then in a warning?

**Comment by lgladdy** [comment]
@ViliusS Your browser might be converting the `&` back to `&amp`; in inspector for you. We only show the warning when we're returning modified code.

**Comment by ViliusS** [comment]
Ah yes, you are right. Dev Tools showed already translated `&`, but viewing through curl I see `&amp;` on the output.

It's strange though that Text Area field doesn't convert it on save. Anyway, that's another issue for another day.

**Comment by lgladdy** [comment]
Hey,

Not converting on save is by design. You might be pasting code into there you want to output raw. ACF makes no assumptions about the type of data being displayed, it just forced escaping on output when you use our `the_field`, `the_sub_field` or the shortcode. Essentially anywhere ACF handles the `echo`
